### ISSUE TITLE
Large files

### ISSUE THREAD

**Issue by markkerzner** [shmsoft/FreeEed#163]
As far as the OutofMemory errors/Java Heap space errors – I think I have a few files OVA, VMDK, VHD that were so huge, it was unable to process those.

**Comment by stucka** [comment]
For what it's worth, I ran into this problem and was able to fix it by explicitly allocating more memory:
https://askubuntu.com/questions/542585/how-to-increase-java-heap-size

First, probably a good idea to check if you've already got any Java options hardcoded. If in Ubuntu VM:
set | grep -i java

If nothing pops up and you want to set a 4-megabyte heap space:
export _JAVA_OPTIONS=-Xmx4096m

To make that occur each time you log in, edit ~/.profile and add the same thing.

**Comment by markkerzner** [comment]
duplicate
