### ISSUE TITLE
Metadata Issues

### ISSUE THREAD

**Issue by alanp5** [shmsoft/FreeEed#183]
It seems that there are some inconsistencies with metadata file that is produced. For example, there are 29 columns in the header however there are 138 columns in some of the lines. 

Additionally it doesn't seem that the "attachment_parent" field is being properly populated. I assume it should have the name of the parent in there but currently it doesn't.

**Comment by markkerzner** [comment]
Hi,

I'd be glad to check if you can provide some additional data, like the load
file you get

Thank you
Mark

Mark Kerzner, President, Elephant Scale <http://elephantscale.com/>
Book a call with me here <http://www.meetme.so/markkerzner>
Mobile: 713-724-2534, Skype: mark.kerzner1

**Comment by alanp5** [comment]
[metadata_Poirier.zip](https://github.com/shmsoft/FreeEed/files/1032042/metadata_Poirier.zip)
I attached the zip of a metadata file I got with the PST I processed.

**Comment by markkerzner** [comment]
Alan,

That is very useful. I would need more, though, can you give me the native
files you were processing? Also, the settings you were using?

I will add the "Support" menu, to submit error reports, but for now, I will
have to rely on your help.

Thank you,
Mark

Mark Kerzner, President, Elephant Scale <http://elephantscale.com/>
Book a call with me here <http://www.meetme.so/markkerzner>
Mobile: 713-724-2534, Skype: mark.kerzner1

**Comment by alanp5** [comment]
The PST i was using was very large (14GB). As for the settings, I wasn't 
using anything special. The only thing I changed was that I wanted all 
the Metadata.

**Comment by markkerzner** [comment]
OK, "All Metadata" - that is helpful

Mark Kerzner, President, Elephant Scale <http://elephantscale.com/>
Book a call with me here <http://www.meetme.so/markkerzner>
Mobile: 713-724-2534, Skype: mark.kerzner1

**Comment by alanp5** [comment]
Just want to check to see if you had any other questions about this. I just ran a test with the latest build on the site and it seems to still be an issue. Let me know if you need any additional examples. Thanks for all your work on this project!

**Comment by markkerzner** [comment]
Yes, please, need additional examples.

Thank you

Mark Kerzner, President, Elephant Scale <http://elephantscale.com/>
Book a call with me here <http://www.meetme.so/markkerzner>
Mobile: 713-724-2534, Skype: mark.kerzner1
Twitter: @elephantscale <https://twitter.com/elephantscale>

**Comment by markkerzner** [comment]
Unable to reproduce the problem
