### ISSUE TITLE
Clean up security alerts

### ISSUE THREAD

**Issue by markkerzner** [shmsoft/FreeEed#204]
Those that show up on GitHub

**Comment by markkerzner** [comment]
Farshid or Mark, whoever gets to it first

**Comment by markkerzner** [comment]
org.apache.tika:tika-core
high severity
 Oct 17, 2018 by GitHub
pom.xml
com.fasterxml.jackson.core:jackson-databind
critical severity
 Oct 16, 2018 by GitHub
freeeed-processing/pom.xml

**Comment by farshidmh** [comment]
all alerts are fixed - 10/17/19
