### ISSUE TITLE
Horizontal scalability

### ISSUE THREAD

**Issue by farshidmh** [shmsoft/FreeEed#218]
i think  having a recursive is not efficient
perhaps a rewrite of this function to make it non-recursive?

**Comment by markkerzner** [comment]
Let's have a list of things to discuss and discuss them at our meeting

Mark Kerzner, President, Elephant Scale <http://elephantscale.com/>,
LinkedIn <https://www.linkedin.com/in/markkerzner/>
Book a call with me here <http://www.meetme.so/markkerzner>
Mobile: 713-724-2534, Skype: mark.kerzner1
Twitter: @elephantscale <https://twitter.com/elephantscale>

**Comment by markkerzner** [comment]
Multithreading gives enough scalability for now
