### ISSUE TITLE
windows release

### ISSUE THREAD

**Issue by farshidmh** [shmsoft/FreeEed#219]
I was thinking since our main audience are lawyers and they are using windows, perhaps we could have an installer version for windows in version 8

**Comment by markkerzner** [comment]
Good idea!

Mark Kerzner, President, Elephant Scale <http://elephantscale.com/>,
LinkedIn <https://www.linkedin.com/in/markkerzner/>
Book a call with me here <http://www.meetme.so/markkerzner>
Mobile: 713-724-2534, Skype: mark.kerzner1
Twitter: @elephantscale <https://twitter.com/elephantscale>

**Comment by markkerzner** [comment]
Part of the overall release
