### ISSUE TITLE
start_services.sh and stop_services.sh

### ISSUE THREAD

**Issue by markkerzner** [shmsoft/FreeEed#246]
It seems convenient to have such scripts in the distribution. Otherwise, the user always has to "start all"

**Comment by farshidmh** [comment]
what if we manage those services from FreeEED UI ?

**Comment by markkerzner** [comment]
Not now. It's normal for distributions to come with such scripts. Less
things hidden and less things automatic.
Mark Kerzner, President, Elephant Scale
<https://t.sidekickopen06.com/s1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5XWPfhMynN7dSsgvQJSG0W56dW9Z7JQs36102?te=W3R5hFj26QkH1W3ZVd9v3zd-ghW3F4Fph1JxwY51V3&si=8000000003820840&pi=362a5df2-db01-4b4c-976c-3a4af40502bc>,
LinkedIn
<https://t.sidekickopen06.com/s1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5XWPfhMynN7dSsgvQJSG0W56dW9Z7JQs36102?te=W3R5hFj4cm2zwW4mKLS-3ZWVWBW3K2-zv1JxwY5W1Lyz993_R5ZJW3XWHT641Rklh0&si=8000000003820840&pi=362a5df2-db01-4b4c-976c-3a4af40502bc>
Book a call with me here
<https://t.sidekickopen06.com/s1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5XWPfhMynN7dSsgvQJSG0W56dW9Z7JQs36102?te=W3R5hFj26QkHmW4mKDt33K3q0fW3JFwQX1LBbZjW3XZ8z64tzCxP0&si=8000000003820840&pi=362a5df2-db01-4b4c-976c-3a4af40502bc>
Mobile: 713-724-2534, Skype: mark.kerzner1
Twitter: @elephantscale
<https://t.sidekickopen06.com/s1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5XWPfhMynN7dSsgvQJSG0W56dW9Z7JQs36102?te=W3R5hFj4cm2zwW4fQ47l4fGCmnW3Fbt5S3K6j0CW3QZn4-4cHbrv21V3&si=8000000003820840&pi=362a5df2-db01-4b4c-976c-3a4af40502bc>

**Comment by markkerzner** [comment]
eDiscovery on a Budget

Scaia AI
View this email in your browser (https://mailchi.mp/ca5e2b9a79a2/ediscovery-on-a-budget-904348?e=b8e8ebc111)
http://elephantscale.com/?utm_campaign=training-followup&utm_medium=email&utm_source=training-followup
Hi shmsoft/FreeEed,

There are more than one million lawyers in the US and at least half of them have never done eDiscovery or do not have sufficient knowledge to do eDiscovery or find it too expensive.

If you identify yourself with this last group, then this webinar is for you. We will show you how to do eDiscovery, understand it, and what’s more - how to use FREE software for it. When you want to up your ante and go with a world-leading review platform, we will show that too.

https://bit.ly/2Raun7U

REGISTER HERE (https://bit.ly/2Raun7U)

Scaia stands for Scalable Artificial Intelligence. We are building AI-based products and we are applying them to document processing, such as eDiscovery.Scaia provides A.I. models trained with corpora of datasets especially tuned for specific use cases in the legal, business, and scientific space.

See you there,
Scaia Team (https://scaia.ai/)




============================================================
** Twitter (http://www.twitter.com/)
** Facebook (http://www.facebook.com)
** Website (http://mailchimp.com)
Copyright © 2020 Scaia, All rights reserved.
 Scaia

Our mailing address is:
Scaia
1 Riverway, Suite 1700
Houston, TX 77071-2602
USA
Want to change how you receive these emails?
You can ** update your preferences (https://elephantscale.us10.list-manage.com/profile?u=689e439c6b1a1e85beb70fff9&id=1448d01e3e&e=b8e8ebc111)
or ** unsubscribe from this list (https://elephantscale.us10.list-manage.com/unsubscribe?u=689e439c6b1a1e85beb70fff9&id=1448d01e3e&e=b8e8ebc111&c=5be048a393)
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=689e439c6b1a1e85beb70fff9&afl=1

**Comment by markkerzner** [comment]
eDiscovery Data Collection

Scaia AI
View this email in your browser (https://mailchi.mp/dd2adbe861a3/ediscovery-data-collection?e=b8e8ebc111)
http://elephantscale.com/?utm_campaign=training-followup&utm_medium=email&utm_source=training-followup
Hi shmsoft/FreeEed,
Data collection is perhaps the most technically rigorous and complex of all the e-discovery phases. It involves the extraction of potentially relevant electronically stored information (ESI) from its native source into a separate repository.

If you wonder about the following
* What are the aspects of data collection in eDiscovery?
* Can I do it myself and how?
* If I use others to do it, what should I be mindful of?

Then this webinar is for you.

https://us02web.zoom.us/webinar/register/4116009539787/WN_afiRMObUR-OB5ofYm0TcXg

Date: 01 Oct Thursday 1 PM CST
REGISTER HERE (https://us02web.zoom.us/webinar/register/4116009539787/WN_afiRMObUR-OB5ofYm0TcXg)  for Free

Scaia stands for Scalable Artificial Intelligence. We are building AI-based products and we are applying them to document processing, such as eDiscovery. Scaia provides A.I. models trained with corpora of datasets especially tuned for specific use cases in the legal, business, and scientific space.

See you there,
Scaia Team (https://scaia.ai/)




============================================================
** Twitter (http://www.twitter.com/)
** Facebook (http://www.facebook.com)
** Website (http://mailchimp.com)
Copyright © 2020 Scaia, All rights reserved.
 Scaia

Our mailing address is:
Scaia
1 Riverway, Suite 1700
Houston, TX 77071-2602
USA
Want to change how you receive these emails?
You can ** update your preferences (https://elephantscale.us10.list-manage.com/profile?u=689e439c6b1a1e85beb70fff9&id=1448d01e3e&e=b8e8ebc111)
or ** unsubscribe from this list (https://elephantscale.us10.list-manage.com/unsubscribe?u=689e439c6b1a1e85beb70fff9&id=1448d01e3e&e=b8e8ebc111&c=2202277e57)
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=689e439c6b1a1e85beb70fff9&afl=1

**Comment by markkerzner** [comment]
eDiscovery Data Collection

Scaia AI
View this email in your browser (https://mailchi.mp/6a53cf51a849/ediscovery-data-collection-904376?e=b8e8ebc111)
http://elephantscale.com/?utm_campaign=training-followup&utm_medium=email&utm_source=training-followup
Hi shmsoft/FreeEed,
Data collection is perhaps the most technically rigorous and complex of all the e-discovery phases. It involves the extraction of potentially relevant electronically stored information (ESI) from its native source into a separate repository.

If you wonder about the following
* What are the aspects of data collection in eDiscovery?
* Can I do it myself and how?
* If I use others to do it, what should I be mindful of?

Then this webinar is for you.

https://us02web.zoom.us/webinar/register/4116009539787/WN_afiRMObUR-OB5ofYm0TcXg

Date: 01 Oct Thursday 1 PM CST
REGISTER HERE (https://us02web.zoom.us/webinar/register/4116009539787/WN_afiRMObUR-OB5ofYm0TcXg)

Scaia stands for Scalable Artificial Intelligence. We are building AI-based products and we are applying them to document processing, such as eDiscovery. Scaia provides A.I. models trained with corpora of datasets especially tuned for specific use cases in the legal, business, and scientific space.

See you there,
Scaia Team (https://scaia.ai/)




============================================================
** Twitter (http://www.twitter.com/)
** Facebook (http://www.facebook.com)
** Website (http://mailchimp.com)
Copyright © 2020 Scaia, All rights reserved.
 Scaia

Our mailing address is:
Scaia
1 Riverway, Suite 1700
Houston, TX 77071-2602
USA
Want to change how you receive these emails?
You can ** update your preferences (https://elephantscale.us10.list-manage.com/profile?u=689e439c6b1a1e85beb70fff9&id=1448d01e3e&e=b8e8ebc111)
or ** unsubscribe from this list (https://elephantscale.us10.list-manage.com/unsubscribe?u=689e439c6b1a1e85beb70fff9&id=1448d01e3e&e=b8e8ebc111&c=3a026576ba)
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=689e439c6b1a1e85beb70fff9&afl=1

**Comment by markkerzner** [comment]
eDiscovery Data Collection

Scaia AI
View this email in your browser (https://mailchi.mp/55fbe9fb06cd/ediscovery-data-collection-904420?e=b8e8ebc111)
http://elephantscale.com/?utm_campaign=training-followup&utm_medium=email&utm_source=training-followup
Hi shmsoft/FreeEed,

Last year, Google made its “Most important upgrade in the last five years (https://t.sidekickopen81.com/s1t/c/5/f18dQhb0S7kF8cVZp8W5nLK-W2zGCwVN8Jbw_8QsRtKMpfW-6d0vQdW16gGzC7SyGLk101?te=W3R5hFj4cm2zwW4mKLS-3Fb2KYW3Fbt5S4kFl2XW43WBDC4hLZLWW3K9dy91S1ngSW1L687_1S3svmW43V0FM3JF5l5W3zgCH01Gyy3-W4fdj3z3P5VwzW3JF5lf3zgF8yW49h9jr3Q_2k7W3P4G2R1GBcksW4cQhz74kCBqm39Jx2&si=8000000003820840π=b9f4745a-b7e7-420d-b293-7488f68c8566) .” It is called “BERT” and it allows AI to understand human language like it was never able to before. BERT opens completely new vistas in eDiscovery, which is all about understanding the language.

Google's "Attention is All You Need" paper paved the way to BERT (Bidirectional Encoder Representations from Transformers). BERT has revolutionized the representation of natural language text for machine learning understanding. BERT itself has inspired a whole family of variants which in some cases are better targeted and improved over the original, although the original BERT has some of its own advantages.

In this webinar, we will look at what makes BERT so important, and discuss how to choose a BERT-based model that best suits your needs.

Date: 12 Nov Thursday, 10 AM PDT/12 PM CST/1 PM EST
REGISTER HERE (https://us02web.zoom.us/webinar/register/WN_aPXzcB36QAyvjj_dF0R3ow)

https://us02web.zoom.us/webinar/register/WN_aPXzcB36QAyvjj_dF0R3ow

Scaia stands for Scalable Artificial Intelligence. We are building AI-based products and we are applying them to document processing, such as eDiscovery. Scaia provides A.I. models trained with corpora of datasets especially tuned for specific use cases in the legal, business, and scientific space.

See you there,
Scaia Team (https://scaia.ai/)




============================================================
** Twitter (http://www.twitter.com/)
** Facebook (http://www.facebook.com)
** Website (http://mailchimp.com)
Copyright © 2020 Scaia, All rights reserved.
 Scaia

Our mailing address is:
Scaia
1 Riverway, Suite 1700
Houston, TX 77071-2602
USA
Want to change how you receive these emails?
You can ** update your preferences (https://elephantscale.us10.list-manage.com/profile?u=689e439c6b1a1e85beb70fff9&id=1448d01e3e&e=b8e8ebc111)
or ** unsubscribe from this list (https://elephantscale.us10.list-manage.com/unsubscribe?u=689e439c6b1a1e85beb70fff9&id=1448d01e3e&e=b8e8ebc111&c=a9cceef27e)
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=689e439c6b1a1e85beb70fff9&afl=1

**Comment by markkerzner** [comment]
eDiscovery Data Collection

Scaia AI
View this email in your browser (https://mailchi.mp/1c81a0b6cd56/ediscovery-data-collection-904432?e=b8e8ebc111)
http://elephantscale.com/?utm_campaign=training-followup&utm_medium=email&utm_source=training-followup
Hi shmsoft/FreeEed,

AI in eDiscovery. Last year, Google made its “Most important upgrade in the last five years (https://t.sidekickopen81.com/s1t/c/5/f18dQhb0S7kF8cVZp8W5nLK-W2zGCwVN8Jbw_8QsRtKMpfW-6d0vQdW16gGzC7SyGLk101?te=W3R5hFj4cm2zwW4mKLS-3Fb2KYW3Fbt5S4kFl2XW43WBDC4hLZLWW3K9dy91S1ngSW1L687_1S3svmW43V0FM3JF5l5W3zgCH01Gyy3-W4fdj3z3P5VwzW3JF5lf3zgF8yW49h9jr3Q_2k7W3P4G2R1GBcksW4cQhz74kCBqm39Jx2&si=8000000003820840π=b9f4745a-b7e7-420d-b293-7488f68c8566) .” It is called “BERT” and it allows AI to understand human language like it was never able to before. BERT opens completely new vistas in eDiscovery, which is all about understanding the language.

Google's "Attention is All You Need" paper paved the way to BERT (Bidirectional Encoder Representations from Transformers). BERT has revolutionized the representation of natural language text for machine learning understanding. BERT itself has inspired a whole family of variants which in some cases are better targeted and improved over the original, although the original BERT has some of its own advantages.

In this webinar, we will look at what makes BERT so important, and discuss how to choose a BERT-based model that best suits your needs.

Date: 12 Nov Thursday, 10 AM PDT/12 PM CST/1 PM EST
REGISTER HERE (https://us02web.zoom.us/webinar/register/WN_aPXzcB36QAyvjj_dF0R3ow)

https://us02web.zoom.us/webinar/register/WN_aPXzcB36QAyvjj_dF0R3ow

Scaia stands for Scalable Artificial Intelligence. We are building AI-based products and we are applying them to document processing, such as eDiscovery. Scaia provides A.I. models trained with corpora of datasets especially tuned for specific use cases in the legal, business, and scientific space.

See you there,
Scaia Team (https://scaia.ai/)




============================================================
** Twitter (http://www.twitter.com/)
** Facebook (http://www.facebook.com)
** Website (http://mailchimp.com)
Copyright © 2020 Scaia, All rights reserved.
 Scaia

Our mailing address is:
Scaia
1 Riverway, Suite 1700
Houston, TX 77071-2602
USA
Want to change how you receive these emails?
You can ** update your preferences (https://elephantscale.us10.list-manage.com/profile?u=689e439c6b1a1e85beb70fff9&id=1448d01e3e&e=b8e8ebc111)
or ** unsubscribe from this list (https://elephantscale.us10.list-manage.com/unsubscribe?u=689e439c6b1a1e85beb70fff9&id=1448d01e3e&e=b8e8ebc111&c=be9fa5004e)
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=689e439c6b1a1e85beb70fff9&afl=1

**Comment by markkerzner** [comment]
https://scaia.ai/
https://scaia.ai/scaia-ediscovery/


** eDiscovery projects require quality, speed, and support. That is what Scaia delivers.
------------------------------------------------------------

Scaia started offering its eDiscovery software for private beta testing. For a limited time, we are giving software keys required to run the software to those who request it by replying to this email.

What is new now?

Scaia offers a supported version of FreeEED for eDiscovery, adds multiplatform install, speed, AI


Here is a comparison table:
https://scaia.ai/download/
To Download, Go Here
Download (https://scaia.ai/scaia-ediscovery/)

What is new in the near future?

The eDiscovery AI components developed by Scaia will be added first to the supported version, and later to the community edition.
Stay tuned.

Thank you,
Mark Kerzner
Founder, SCAIA

============================================================
** (https://scaia.ai/)

This email was sent to ***@***.*** ***@***.***)
why did I get this? (https://elephantscale.us10.list-manage.com/about?u=689e439c6b1a1e85beb70fff9&id=94f6a01e87&e=b8e8ebc111&c=094c87c747)     unsubscribe from this list (https://elephantscale.us10.list-manage.com/unsubscribe?u=689e439c6b1a1e85beb70fff9&id=94f6a01e87&e=b8e8ebc111&c=094c87c747)     update subscription preferences (https://elephantscale.us10.list-manage.com/profile?u=689e439c6b1a1e85beb70fff9&id=94f6a01e87&e=b8e8ebc111&c=094c87c747)
Elephant Scale INC . 7522 Apache Plume Dr . Houston, TX 77071-2602 . USA

**Comment by markkerzner** [comment]
FreeED - Advanced Free eDoscovery tool 

https://github.com/shmsoft/FreeEed


** It may sound like a magic fairy tale, but it exists. Although free, it may still be the best for your needs. It may also be the most advanced because it incorporates AI capabilities.
------------------------------------------------------------

Ready to run:
CLICK HERE (https://github.com/shmsoft/FreeEed)

============================================================
** Twitter (https://twitter.com/markkerzner)
** Website (https://github.com/shmsoft/FreeEed)
** LinkedIn (https://www.linkedin.com/in/markkerzner/)

This email was sent to ***@***.*** ***@***.***)
why did I get this? (https://elephantscale.us10.list-manage.com/about?u=689e439c6b1a1e85beb70fff9&id=91f421aef2&e=b8e8ebc111&c=9a9851459a)     unsubscribe from this list (https://elephantscale.us10.list-manage.com/unsubscribe?u=689e439c6b1a1e85beb70fff9&id=91f421aef2&e=b8e8ebc111&c=9a9851459a)     update subscription preferences (https://elephantscale.us10.list-manage.com/profile?u=689e439c6b1a1e85beb70fff9&id=91f421aef2&e=b8e8ebc111&c=9a9851459a)
Scaia AI . 7522 Apache Plume Dr . Houston, TX 77071-2602 . USA

**Comment by markkerzner** [comment]
Webinar
View this email in your browser (https://mailchi.mp/f8be37e0862e/summarization-904728?e=b8e8ebc111)
------------------------------------------------------------
http://elephantscale.com/?utm_campaign=training-followup&utm_medium=email&utm_source=training-followup
Hi shmsoft/FreeEed,

https://us02web.zoom.us/webinar/register/7216457127832/WN_b67-hDXPQhShHwgcaFIGdw


** Overview
------------------------------------------------------------

This webinar will show you how to add an automatically generated summary of each document. That's an excellent time-saver in the document review. We will also show you how to detect PII. You cannot be too cautious with PII because of the recent regulatory changes, such as GDPR, CCPA, and LGPD.

For FreeEed fans, it is also a chance to ask about the software's current development state and the roadmap.

See you there!

Date: March 02, Wednesday
Time:  10 AM PST / 12 PM CST / 1 PM EST
Register here (https://us02web.zoom.us/webinar/register/7216457127832/WN_b67-hDXPQhShHwgcaFIGdw)

============================================================
** Twitter (https://twitter.com/scaia11)
** https://scaia.ai/ (https://scaia.ai/)

This email was sent to ***@***.*** ***@***.***)
why did I get this? (https://elephantscale.us10.list-manage.com/about?u=689e439c6b1a1e85beb70fff9&id=91f421aef2&e=b8e8ebc111&c=020fd1941c)     unsubscribe from this list (https://elephantscale.us10.list-manage.com/unsubscribe?u=689e439c6b1a1e85beb70fff9&id=91f421aef2&e=b8e8ebc111&c=020fd1941c)     update subscription preferences (https://elephantscale.us10.list-manage.com/profile?u=689e439c6b1a1e85beb70fff9&id=91f421aef2&e=b8e8ebc111&c=020fd1941c)
Scaia AI . 7522 Apache Plume Dr . Houston, TX 77071-2602 . USA

**Comment by markkerzner** [comment]
Webinar
View this email in your browser (https://mailchi.mp/fa04783cf18c/summarization-904736?e=b8e8ebc111)
------------------------------------------------------------
http://elephantscale.com/?utm_campaign=training-followup&utm_medium=email&utm_source=training-followup
Hi ,

https://us02web.zoom.us/webinar/register/7216457127832/WN_b67-hDXPQhShHwgcaFIGdw


** Overview
------------------------------------------------------------

This webinar will show you how to add an automatically generated summary of each document. That's an excellent time-saver in the document review. We will also show you how to detect PII. You cannot be too cautious with PII because of the recent regulatory changes, such as GDPR, CCPA, and LGPD.

For FreeEed fans, it is also a chance to ask about the software's current development state and the roadmap.

See you there!

Date: March 02, Wednesday
Time:  10 AM PST / 12 PM CST / 1 PM EST
Register here (https://us02web.zoom.us/webinar/register/7216457127832/WN_b67-hDXPQhShHwgcaFIGdw)

============================================================
** Twitter (https://twitter.com/scaia11)
** https://scaia.ai/ (https://scaia.ai/)

This email was sent to ***@***.*** ***@***.***)
why did I get this? (https://elephantscale.us10.list-manage.com/about?u=689e439c6b1a1e85beb70fff9&id=94f6a01e87&e=b8e8ebc111&c=1876f581b1)     unsubscribe from this list (https://elephantscale.us10.list-manage.com/unsubscribe?u=689e439c6b1a1e85beb70fff9&id=94f6a01e87&e=b8e8ebc111&c=1876f581b1)     update subscription preferences (https://elephantscale.us10.list-manage.com/profile?u=689e439c6b1a1e85beb70fff9&id=94f6a01e87&e=b8e8ebc111&c=1876f581b1)
Elephant Scale INC . 7522 Apache Plume Dr . Houston, TX 77071-2602 . USA

**Comment by markkerzner** [comment]
Webinar
View this email in your browser (https://mailchi.mp/468c53d9c503/summarization-904744?e=b8e8ebc111)
------------------------------------------------------------
http://elephantscale.com/?utm_campaign=training-followup&utm_medium=email&utm_source=training-followup
Hi shmsoft/FreeEed,

https://us02web.zoom.us/webinar/register/7216457127832/WN_b67-hDXPQhShHwgcaFIGdw


** Overview
------------------------------------------------------------

This webinar will show you how to add an automatically generated summary of each document. That's an excellent time-saver in the document review. We will also show you how to detect PII. You cannot be too cautious with PII because of the recent regulatory changes, such as GDPR, CCPA, and LGPD.

For FreeEed fans, it is also a chance to ask about the software's current development state and the roadmap.

See you there!

Date: March 02, Wednesday
Time:  10 AM PST / 12 PM CST / 1 PM EST
Register here (https://us02web.zoom.us/webinar/register/7216457127832/WN_b67-hDXPQhShHwgcaFIGdw)

============================================================
** Twitter (https://twitter.com/scaia11)
** https://scaia.ai/ (https://scaia.ai/)

This email was sent to ***@***.*** ***@***.***)
why did I get this? (https://elephantscale.us10.list-manage.com/about?u=689e439c6b1a1e85beb70fff9&id=91f421aef2&e=b8e8ebc111&c=3649173285)     unsubscribe from this list (https://elephantscale.us10.list-manage.com/unsubscribe?u=689e439c6b1a1e85beb70fff9&id=91f421aef2&e=b8e8ebc111&c=3649173285)     update subscription preferences (https://elephantscale.us10.list-manage.com/profile?u=689e439c6b1a1e85beb70fff9&id=91f421aef2&e=b8e8ebc111&c=3649173285)
Scaia AI . 7522 Apache Plume Dr . Houston, TX 77071-2602 . USA

**Comment by markkerzner** [comment]
News from FreeEed - Casify

View this email in your browser (https://mailchi.mp/5907063372b7/news-from-freeeed-casify?e=b8e8ebc111)
https://getcasify.com/


** Eliminate your stacks of paper files!
------------------------------------------------------------

Brought to you by the FreeEed team! Casify (https://getcasify.com/)  is the only case management software designed specifically for the sole practitioner and small office defense attorney. We wanted to let you know how Casify (https://getcasify.com/)  has helped other attorneys and what we can do to help you:

"The clutter in my office has disappeared, and I never have to search for misplaced files. Instead of carrying my files to court, I only carry my laptop."
Clint Parish
Solo Practitioner & Casify User
Sonora, CA

The team at Casify wants to offer you a free personal training session so you, too, can learn how simple it is to use Casify and leverage it to help streamline your law practice.

Simply reply to this email, and we will arrange a time for a free personal training session with us.

Sincerely,
The Casify Team

============================================================
** (https://getcasify.com/)

This email was sent to ***@***.*** ***@***.***)
why did I get this? (https://elephantscale.us10.list-manage.com/about?u=689e439c6b1a1e85beb70fff9&id=91f421aef2&e=b8e8ebc111&c=397539b46a)     unsubscribe from this list (https://elephantscale.us10.list-manage.com/unsubscribe?u=689e439c6b1a1e85beb70fff9&id=91f421aef2&e=b8e8ebc111&c=397539b46a)     update subscription preferences (https://elephantscale.us10.list-manage.com/profile?u=689e439c6b1a1e85beb70fff9&id=91f421aef2&e=b8e8ebc111&c=397539b46a)
Scaia AI . 7522 Apache Plume Dr . Houston, TX 77071-2602 . USA
