### ISSUE TITLE
No extracted PII with users files.

### ISSUE THREAD

**Issue by Steven-Data** [shmsoft/FreeEed#318]
We need your help on checking if you get any error from Inabia API or any bug from you side?

I was trying to reproduce and cross-test the error that the user got with FreeEed and Inabia API. It might be a bug from FreeEed side because I used the extracted text in the metadata and fed into API directly, and it works fine. So, please help us check from your side as well.

One if the user's files:
[Word sample-data.pdf](https://github.com/shmsoft/FreeEed/files/7956761/Word.sample-data.pdf)

The text that extracted by FreeEed:
<img width="909" alt="Screen Shot 2022-01-27 at 6 17 00 PM" src="https://user-images.githubusercontent.com/55162706/151508332-a9e4aadb-2acd-47f5-abbf-10ae765a8c35.png">
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/55162706/151508386-c6a56a7f-b71b-44fb-8c7c-8da7a390bd02.png">

Test text: (from the metadata of FreeEed):
[Input.txt](https://github.com/shmsoft/FreeEed/files/7956772/Input.txt)

The input and the output of Inabia API:
<img width="1459" alt="Screen Shot 2022-01-27 at 5 51 00 PM" src="https://user-images.githubusercontent.com/55162706/151508548-f56e23bd-55e6-4560-a807-1e6c8fcf0bd6.png">
<img width="1457" alt="Screen Shot 2022-01-27 at 5 53 40 PM" src="https://user-images.githubusercontent.com/55162706/151508561-77df0a56-a832-4ab6-b1c8-0ad66401ef5a.png">

**Comment by markkerzner** [comment]
All is good now
