### ISSUE TITLE
Test with MBOX

### ISSUE THREAD

**Issue by markkerzner** [shmsoft/FreeEed#53]

**Comment by markkerzner** [comment]
Was it ever tested?

**Comment by alanmp55** [comment]
I just tried processing a 4gb MBOX and it seems to only recognized the file as a text file. This results in only a single file being generated.

**Comment by alanmp55** [comment]
To add to this in ubuntu, it doesn't recognize that the file is an mbox. In windows I get the following error:
2019-07-02 17:35:49 1673401 [Thread-3] WARN  org.freeeed.services.ContentTypeMapping  - Not found file type for content type: application/mbox

hope this helps.
